spring:
  application:
    name: spring-cloud-config-server-7002
  datasource:
    url: jdbc:mysql://localhost:3306/web2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a0909007892
  profiles:
    active: native
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common-config
server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,*
