spring:
  application:
    name: spring-cloud-api-gateway-7004
  config:
    import: optional:configserver:http://localhost:7002
server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/